Iter 2/scheduler
TheUcheojor/SYSC3303_ElevatorControlSystem pull request #21
Opened 2022-02-16 01:16 UTC by rfife

This PR adds the required functionality for the use case sequence in iteration 2!

Functionality added:
- Changed message channels to use a bounded queue (allows for more messages while preventing overflowing message channels)
- Added a proper job queue for the elevator
- Added 5 commands for controlling the elevator 
- > these commands allow us to serve job requests

This PR assumes some changes in the elevator including:
- The elevator needs to notify the scheduler whenever it is at a floor
- The elevator needs to respond to the new commands issued by the scheduler
- > could just be a elevator status message
- > lets the scheduler know the command was processed, and the elevator is in the proper state

Work to do in iteration 3:
- scale the elevator logic to work for multiple elevators

2022-02-16 01:36 UTC, FavourO2 commented on src/common/messages/MessageType.java
> +	 * A message indicating that the elevator is leaving the floor
I Need to update the comment

2022-02-16 01:39 UTC, FavourO2 approved these changes

2022-02-16 02:16 UTC, TheUcheojor requested changes

2022-02-16 02:16 UTC, TheUcheojor commented on src/ElevatorSubsystem/ElevatorCar.java
When we introduce UDP, are we planning on sending multiple messages in one packet?

I am not sure how that pans out with the scheduler and elevator interactions. 

Perhaps, you could highlight the reasoning behind the change.

2022-02-16 02:16 UTC, TheUcheojor commented on src/Scheduler/Scheduler.java
> +	private ArrayList<JobRequest> unassignedJobRequests = new ArrayList<>();
I think JavaDocs provide more readability. 

If time permits, I would consider adding them for all functions and global variables. It goes a long way. The java docs can be simple too.

Let me know if there are critical reasons why we should not use java docs.

2022-02-16 02:16 UTC, TheUcheojor commented on src/Scheduler/Scheduler.java
> +			if(currRequest.getFloorId() == elevatorFloorNumber) {
Where does _elevatorFloorNumber_ get initialized?

2022-02-16 02:16 UTC, TheUcheojor commented on src/Scheduler/Scheduler.java
> +
I think adding an explanation for the while block would be helpful

2022-02-16 02:16 UTC, TheUcheojor commented on src/Scheduler/Scheduler.java
> +			if(currRequest.getFloorId() == elevatorFloorNumber) {
From what I understand, served job means that you arrived at the destination floor. Hence, that is why we add remove the job and set the jobServed flag to true.

But does currRequest.getFloorId() get the source or destination floor id? I think it gets the source which would make the conditional invalid

2022-02-16 02:16 UTC, TheUcheojor commented on src/Scheduler/Scheduler.java
> +
I like the idea of support threads in the scheduler but _what prevents the main Scheduler thread from addressing non-blocking elevator requests?_

 I see that the scheduler manager thread performs non-blocking tasks. Creating support threads for non-blocking tasks seem counter-intuitive. I thinks it adds unnecessary overhead.

I agree that the Scheduler may need support threads when performing blocking tasks like a timing error detection. The timing error detection gives the elevator a maximum amount of time to respond. Since this task is blocking (we would have to use sleep() ), we do not want to keep the scheduler on hold. Hence, we create a support thread.

Let me know your thoughts tho

2022-02-16 02:16 UTC, TheUcheojor commented on src/Scheduler/Scheduler.java
> +	private void startJob() {
The project outline details that the elevator will notify the scheduler at every floor. 

How do we plan on addressing those notifications?

It may not be important now, but addressing now may save us a lot of refactoring

2022-02-16 02:16 UTC, TheUcheojor commented on src/ElevatorSubsystem/ElevatorCar.java
I see that we have cases whereby we send stop elevator and open door commands.

When we introduce UDP, would those be separate packets or a packet with an array of messages?

2022-02-16 02:16 UTC, TheUcheojor commented on src/SystemExecutor.java
> +	public static final int DEFAULT_MESSAGE_QUEUE_SIZE = 10;
If the queue size is the same for all, it may be clean to place the variable in the MessageChannel

2022-02-16 02:16 UTC, TheUcheojor commented on src/common/SchedulerCommand.java
> +/**
I like the idea of the scheduler command enum.

That separation between the SchedulerCommand and MessageType enums is going to be a life-saver down the line.

2022-02-16 02:16 UTC, TheUcheojor commented on src/common/messages/MessageChannel.java
>  public class MessageChannel {
Java doc :)

2022-02-16 02:16 UTC, TheUcheojor commented on src/common/messages/MessageType.java
> +	SCHEDULER_ELEVATOR_COMMAND,
The java doc and the enum kinda conflict. 

It looks like this message should probably be updated

2022-02-16 02:16 UTC, TheUcheojor commented on src/common/messages/floor/JobRequest.java
>  public class JobRequest extends Message {
Java Doc :)

2022-02-16 02:16 UTC, TheUcheojor commented on src/common/messages/scheduler/SchedulerElevatorCommand.java
> + * This class stores a command to be sent to the elevator from the scheduler
This is probably the description that we would want for SCHEDULER_ELEVATOR_COMMAND enum in MessageType

2022-02-16 18:08 UTC, rfife commented on src/ElevatorSubsystem/ElevatorCar.java
UDP is unreliable so separate packets scares me, would be better for elevator to stay idle then only complete 1/2 commands.

2022-02-16 18:38 UTC, rfife commented on src/Scheduler/Scheduler.java
> +
We wait for an elevator request which is a blocking task. 

**reminder: add a gate to the main scheduler thread preventing reception of elevator messages outside of managing thread when active

2022-02-17 01:15 UTC, rfife commented on src/Scheduler/Scheduler.java
> +	private void startJob() {
@Jakerem1 @delightoluwayemi

2022-02-17 01:30 UTC, rfife commented on src/common/messages/scheduler/SchedulerElevatorCommand.java
> + * This class stores a command to be sent to the elevator from the scheduler
@FavourO2

2022-02-17 03:52 UTC, TheUcheojor commented on src/common/messages/MessageType.java
> +	ELEVATOR_TRANSPORT_REQUEST,
ELEVATOR_TRANSPORT_REQUEST and ELEVATOR_FLOOR_REQUEST can easily be misinterpreted.

Should probably JavaDoc to clarify intentions.

2022-02-17 03:54 UTC, TheUcheojor commented on src/common/messages/elevator/ElevatorTransportRequest.java
> +	ElevatorTransportRequest(int destinationFloor, int elevatorId, Direction direction) {
missing public keyword

2022-02-17 04:08 UTC, TheUcheojor commented on src/common/messages/floor/ElevatorFloorRequest.java
> +public class ElevatorFloorRequest extends Message implements ElevatorJobMessage {
Like I mentioned, the classes are super similar.

Consider renaming to FloorPassengerElevatorRequest.

2022-02-17 04:10 UTC, TheUcheojor commented on src/common/messages/floor/ElevatorFloorRequest.java
> +public class ElevatorFloorRequest extends Message implements ElevatorJobMessage {
In theory, you could make ElevatorJobMessage extend Message and implement the required functions there.

That way you do not have repeat yourself.

2022-02-17 04:14 UTC, TheUcheojor reviewed
Overall solid but minor tweaks probably needed.

2022-02-17 04:15 UTC, TheUcheojor approved these changes

2022-02-17 22:41 UTC, merged